'use client';
import {useState,useEffect} from 'react';
import {ArrowRight,Wind,Droplets,Mountain,Flame,Check,Play,Eye,RotateCcw} from 'lucide-react';
import {characters,nations,words,practice,sentences,type Level} from '@/data/content';
import {Speak,AnswerCard,SentenceBuilder} from './shared';
import WorldPractice from './WorldPractice';
import TalkQuest from './TalkQuest';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
export {default as Heroes} from './Heroes';
const icons={water:Droplets,earth:Mountain,fire:Flame,air:Wind};
export function World({level}:{level:Level}){const [view,setView]=useState('map');const [nation,setNation]=useState('water');const [tour,setTour]=useState<string[]>(['water']);const n=nations.find(n=>n.id===nation)!;const Icon=icons[n.id as keyof typeof icons];return <><div className="view-switch"><button aria-pressed={view==='map'} onClick={()=>setView('map')}>Explore</button><button aria-pressed={view==='practice'} onClick={()=>setView('practice')}>Find their home</button></div><div className="map-layout" hidden={view!=='map'}><div className="map-panel"><div className="map-image"><img src="/assets/world-map.png" alt="World map: Water Tribes at the poles, Fire Nation islands in the west, Earth Kingdom in the east, and four Air Temples."/><span className="map-compass">N ↑</span><button className="map-pin water north" onClick={()=>{setNation('water');setTour([...new Set([...tour,'water'])])}}>Northern Water Tribe</button><button className="map-pin water south" onClick={()=>{setNation('water');setTour([...new Set([...tour,'water'])])}}>Southern Water Tribe</button><button className="map-pin fire west" onClick={()=>{setNation('fire');setTour([...new Set([...tour,'fire'])])}}>Fire Nation</button><button className="map-pin earth east" onClick={()=>{setNation('earth');setTour([...new Set([...tour,'earth'])])}}>Earth Kingdom</button><button className="map-pin air temple" onClick={()=>{setNation('air');setTour([...new Set([...tour,'air'])])}}>Air Temples</button></div><p className="map-caption">Explore the nations using the labels. Air Temples are in four different regions.</p><Tabs value={nation} onValueChange={v=>{setNation(v as string);setTour([...new Set([...tour,v as string])])}}><TabsList className="element-tabs" aria-label="Four elements">{nations.map(x=>{const I=icons[x.id as keyof typeof icons];return <TabsTrigger key={x.id} value={x.id}><I size={24}/>{x.id}{tour.includes(x.id)&&<Check size={13}/>}</TabsTrigger>})}</TabsList></Tabs></div><div className="nation-card" key={nation}><img src={'/assets/'+n.id+'.png'} alt={'Illustrated '+n.home}/><div className="nation-info"><Icon style={{color:n.color}} size={28}/><h2>{n.name}</h2><p className="nation-home">{n.home}</p><p>{level==='explorer'?n.sentence:n.detail}</p><div className="talk-strip">{n.people} can bend {n.id}.</div><Speak text={n.name+'. '+n.sentence}/></div></div></div>{view==='practice'&&<WorldPractice level={level}/>}</>}
export {default as Words} from './Words';
export function Watch({level}:{level:Level}){const [view,setView]=useState('movie');const [seen,setSeen]=useState<string[]>([]);const [url,setUrl]=useState('');const [reveal,setReveal]=useState(false);useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);const cues=level==='explorer'?['Aang','Katara','Sokka','Appa']:['The discovery in the ice','Iroh teaching Zuko','Penguin sledding','The abandoned ship'];return <><div className="view-switch"><button aria-pressed={view==='movie'} onClick={()=>setView('movie')}>Movie</button><button aria-pressed={view==='talk'} onClick={()=>setView('talk')}>Watch & talk</button></div><div className="cinema" hidden={view!=='movie'}><img src="/assets/water.png" alt="Snowy Southern Water Tribe village"/>{url?<video controls src={url} aria-label="Your selected episode video"/>:<div className="cinema-content"><div className="play-medallion"><Play size={34}/></div><p className="eyebrow">LIGHTS DOWN · CURIOSITY UP</p><h2>The Boy in the Iceberg</h2><p>Use your own episode video or watch on your usual service.</p><label className="gold-button file-button">Open a video file<input type="file" accept="video/*" onChange={e=>{const file=e.target.files?.[0];if(file)setUrl(URL.createObjectURL(file))}}/></label><small>The file stays on this device. It is not uploaded.</small></div>}</div><div className="watch-grid" hidden={view!=='talk'}><div className="panel"><p className="eyebrow">FIRST WATCH</p><h2>{level==='explorer'?'Who can you see?':'What happens to the boy?'}</h2><p>{level==='explorer'?'Point to a character when you see them. Enjoy the story first.':'Watch for the main story. What changes after Katara and Sokka find Aang?'}</p><div className="watch-checks">{cues.map(c=><button aria-pressed={seen.includes(c)} className={seen.includes(c)?'selected':''} key={c} onClick={()=>setSeen(seen.includes(c)?seen.filter(x=>x!==c):[...seen,c])}><span className="check-box">{seen.includes(c)&&<Check size={16}/>}</span>{c}</button>)}</div></div><div className="panel"><p className="eyebrow">PAUSE & TALK · OPTIONAL REPLAY</p><h2>One small question.</h2><ul>{(level==='explorer'?['After the ice opens: “Who is this?”','When Appa appears: “Can he fly?”','At the old ship: “Is it safe?”']:['After the ice opens: “How does Katara help?”','At the village: “How does Sokka feel about Aang?”','At the ship: “Why is it dangerous?”']).map(c=><li key={c}>{c}</li>)}</ul><button className="soft-button" onClick={()=>setReveal(!reveal)}>{reveal?'Hide':'Show'} teacher prompts</button>{reveal&&<p className="hint">Aang is the boy. Appa can fly. Sokka is suspicious of Aang. The abandoned ship has traps. Accept simple words, gestures or complete sentences at the learner’s level.</p>}</div></div></>}
export function Challenge({level}:{level:Level}){const [view,setView]=useState('story');const [q,setQ]=useState(0);const [done,setDone]=useState(false);const [sentence,setSentence]=useState(0);const [round,setRound]=useState(0);return <><p className="lead">{level==='explorer'?'Remember the heroes. Build a sentence. Tell a friend.':'Follow the story. Explain your answers. Make your own sentences.'}</p><div className="view-switch"><button aria-pressed={view==='story'} onClick={()=>setView('story')}>Story check</button><button aria-pressed={view==='sentence'} onClick={()=>setView('sentence')}>Build a sentence</button><button aria-pressed={view==='talk'} onClick={()=>setView('talk')}>Talk together</button></div>{view==='talk'&&<TalkQuest level={level}/>}<div className="challenge-grid" hidden={view==='talk'}><div hidden={view!=='story'}><p className="eyebrow">STORY CHECK · {q+1} / {practice[level].length}</p><AnswerCard key={q+'-'+round} question={practice[level][q]} onResult={()=>setDone(true)}/><button className="gold-button" disabled={!done} onClick={()=>{setQ((q+1)%practice[level].length);setDone(false);setRound(round+1)}}>Next question <ArrowRight size={18}/></button></div><div hidden={view!=='sentence'}><SentenceBuilder key={sentence} sentence={sentences[level][sentence]}/><button className="text-button" onClick={()=>setSentence((sentence+1)%sentences[level].length)}><RotateCcw size={16}/> Another sentence</button><div className="talk-strip"><strong>Make it yours</strong><p>{level==='explorer'?'Choose a hero. Say their name, one thing they have got and one thing they can do.':'Which character would you like as a friend? Say why. Then retell three events with first, then and finally.'}</p></div></div></div></>}
