'use client';
import {useEffect,useLayoutEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowLeft,Pause,Play,Volume2,Maximize,Wind,RotateCcw} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {cargo,missions,targetFor,rolesFor,gridPaths,canMove,flightObjects,iceOrders,iceStops,optimalIceMoves} from './expedition-state';
import './expedition.css';
import {jumpPose,castPose,driftItems,JUMP_SECONDS,CAST_SECONDS,type Jump,type WaterCast} from './expedition-motion';
const noun=(item:string)=>item==='boots'?'a pair of boots':'a '+item;
const art='/assets/expedition/';
type Run={building:boolean;jump:Jump|null;cast:WaterCast|null;time:number;y:number;aim:number;count:number;hits:number;used:number[];pos:number;bridge:boolean;carrying:boolean;moves:number;selected:string;deliveries:string[]};
const fresh=():Run=>({building:false,jump:null,cast:null,time:0,y:48,aim:50,count:0,hits:0,used:[],pos:24,bridge:false,carrying:false,moves:0,selected:'',deliveries:[]});
export default function ExpeditionGame(){
 const [round,setRound]=useState(0),[phase,setPhase]=useState<'intro'|'brief'|'play'|'result'|'end'>('intro'),[run,setRun]=useState<Run>(fresh),[pupils,setPupils]=useState(12),[easy,setEasy]=useState(true),[help,setHelp]=useState(true),[paused,setPaused]=useState(false),[score,setScore]=useState(0),[notice,setNotice]=useState(''),[restart,setRestart]=useState(false);
 const grid=useRef<HTMLDivElement>(null);const [gridSize,setGridSize]=useState({width:1000,height:400});
 useLayoutEffect(()=>{const element=grid.current;if(!element)return;const observer=new ResizeObserver(([entry])=>setGridSize({width:entry.contentRect.width,height:entry.contentRect.height}));observer.observe(element);return()=>observer.disconnect()},[phase,round]);
 const [reduced,setReduced]=useState(false);
 useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)');setReduced(m.matches);const fn=()=>setReduced(m.matches);m.addEventListener('change',fn);return()=>m.removeEventListener('change',fn)},[]);
 useEffect(()=>{const atlas=new Image();atlas.src=art+'katara-jump-atlas.png';const waterAtlas=new Image();waterAtlas.src=art+'water-flow-atlas.png';const bending=new Image();bending.src=art+'katara-bend-atlas.png';for(const name of ['katara-jump','water-flow'])for(let i=0;i<8;i++){const image=new Image();image.src=art+name+'-'+i+'.png'}},[]);
 const handlers=useRef({move:(n:number)=>{},catchIt:()=>{},pos:24});
 const keys=useRef(new Set<string>()),stage=useRef<HTMLDivElement>(null);const mission=Math.floor(round/3),part=round%3,order=iceOrders[part][Math.min(run.count,2)],target=mission===0?order.item:targetFor(round),data=missions[mission],path=gridPaths[part],objects=flightObjects(round),active=phase==='play'&&!paused&&!restart;
 function landJump(){setRun(s=>!s.jump?s:{...s,jump:null,pos:s.jump.to,carrying:s.carrying,moves:s.moves+1})}
 function anchor(index:number){const w=gridSize.width,h=gridSize.height,cellW=w*.1075,cellH=h/4,size=Math.min(cellW,cellH);return {x:(index%8*12.75+5.375),y:(Math.floor(index/8)*cellH+(cellH-size)/2+size*.43+w*.13*(20/512))/h*100}}
 const pose={...jumpPose(run.pos,run.jump,reduced),...anchor(run.pos)},water=run.cast?castPose(run.cast):null;
 const [shoreSize,setShoreSize]=useState({width:1280,height:720});
 useLayoutEffect(()=>{const el=stage.current;if(!el)return;const observer=new ResizeObserver(([entry])=>setShoreSize({width:entry.contentRect.width,height:entry.contentRect.height}));observer.observe(el);return()=>observer.disconnect()},[]);
 const shoreScale=Math.max(shoreSize.width/1672,shoreSize.height/941);const shore={x:(shoreSize.width-1672*shoreScale)/2+1672*.26*shoreScale,y:(shoreSize.height-941*shoreScale)/2+941*.71*shoreScale,size:230*shoreScale};
 const speed=easy?13:20;const playerRoles=rolesFor(mission===0?round+run.count:round,pupils);
 function say(text:string){if(!('speechSynthesis' in window)){setNotice('Teacher: please read the request aloud.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.8;speechSynthesis.speak(u)}
 function finish(){setScore(s=>s+Math.max(1,3-Math.floor((mission===0?Math.max(0,run.moves-optimalIceMoves(part)):run.hits)/3)));setPhase('result')}
 function move(to:number){if(!active||run.jump||run.building)return;if(!canMove(run.pos,to,path,run.bridge)){setNotice('Find a neighbouring ice floe. Bend water to open the missing crossing.');return}setRun(s=>s.jump?s:{...s,jump:{from:s.pos,to,elapsed:0}});setNotice('')}
 function catchIt(){if(!active||mission!==1||run.cast)return;const hit=driftItems(run.time,round,easy,cargo).find(o=>Math.abs(o.x-run.aim)<(easy?10:7)&&o.kind===target);setRun(s=>s.cast?s:{...s,cast:{elapsed:0,x:hit?.x??s.aim,y:hit?.y??60,kind:hit?.kind??null,id:hit?.id??-1}});setNotice(hit?'Hold on! Katara is bringing it ashore.':'Watch the water. Try aiming under the '+target+'.')}
 handlers.current={move,catchIt,pos:run.pos};
 useEffect(()=>{if(!active)return;let id=0,last=0;function tick(now:number){const dt=last?Math.min((now-last)/1000,.05):0;last=now;setRun(s=>{let n={...s,time:s.time+dt};if(s.cast){const elapsed=s.cast.elapsed+dt;if(elapsed>=CAST_SECONDS){n.cast=null;if(s.cast.kind)n.count++;else n.hits++}else n.cast={...s.cast,elapsed}}if(mission===2){const direction=(keys.current.has('ArrowDown')?1:0)-(keys.current.has('ArrowUp')?1:0);n.y=Math.max(12,Math.min(84,s.y+direction*dt*44+(easy?0:Math.sin(s.time)*dt*5)));const camera=n.time*speed;for(const o of objects){if(s.used.includes(o.id)||Math.abs(o.x-camera-22)>5||Math.abs(o.y-n.y)>9)continue;n.used=[...n.used,o.id];if(o.kind==='cloud'){n.hits++;n.y=Math.min(84,n.y+11)}else if(o.kind===target)n.count++}if(camera>930){n.time=0;n.used=[]}}return n});id=requestAnimationFrame(tick)}id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id)},[active,mission,round,easy,reduced]);
 useEffect(()=>{if(!active)return;if((mission===0&&run.count>=3)||(mission===1&&run.count>=3)||(mission===2&&run.count>=3)||(mission===3&&run.deliveries.length===3))finish()},[run,active]);
 useEffect(()=>{function down(e:KeyboardEvent){if(!active||(e.target as HTMLElement).closest('input,select,a,[role="dialog"]'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key)){e.preventDefault();keys.current.add(e.key);if(mission===0&&!e.repeat)handlers.current.move(handlers.current.pos+({ArrowUp:-8,ArrowDown:8,ArrowLeft:-1,ArrowRight:1}[e.key]||0));if(mission===1&&e.key===' '&&!e.repeat)handlers.current.catchIt();if(mission===1)setRun(s=>({...s,aim:Math.max(8,Math.min(92,s.aim+(e.key==='ArrowLeft'?-4:e.key==='ArrowRight'?4:0)))}))}}function up(e:KeyboardEvent){keys.current.delete(e.key)}function blur(){keys.current.clear();setPaused(true)}window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);keys.current.clear()}},[active,mission]);
 function point(e:React.PointerEvent<HTMLElement>){if(!active||(e.target as HTMLElement).closest('button'))return;const r=e.currentTarget.getBoundingClientRect();if(mission===1)setRun(s=>({...s,aim:Math.max(8,Math.min(92,(e.clientX-r.left)/r.width*100))}));if(mission===2)setRun(s=>({...s,y:Math.max(12,Math.min(84,(e.clientY-r.top)/r.height*100))}))}
 function deliver(person:number){if(!active||!run.selected)return;const wanted=cargo[(part+person)%5];if(run.deliveries.includes(String(person)))return;if(run.selected===wanted){setRun(s=>({...s,selected:'',deliveries:[...s.deliveries,String(person)]}));setNotice('Thank you! You helped '+['Katara','Sokka','Aang'][person]+'.')}else{setRun(s=>({...s,hits:s.hits+1}));setNotice('Listen again. '+['Katara','Sokka','Aang'][person]+' needs '+wanted+'.')}}
 return <main className={'exp-page '+(!active?'motion-paused':'')}><header className="exp-header"><a href="/words"><ArrowLeft size={17}/> Word camp</a><strong><Wind size={22}/> THE SOUTH POLE EXPEDITION</strong><div><button onClick={()=>setPaused(!paused)} aria-label={paused?'Resume':'Pause'}>{paused?<Play/>:<Pause/>}</button><button aria-label="Full screen" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.()}}><Maximize/></button><button aria-label="Restart expedition" onClick={()=>setRestart(true)}><RotateCcw/></button></div></header>
 <section className="exp-scene" ref={stage} onPointerDown={point} onPointerMove={e=>{if(e.buttons)point(e)}} style={{backgroundImage:mission===3?"url('/assets/water.png')":undefined,backgroundPosition:mission===2?`${50+Math.sin(run.time/80)*45}% center`:'center'}}>
 <div className="exp-top"><span>EXPLORER · {mission+1}/4</span><span>{score} expedition stars · Round {round+1}/12</span></div>
 {phase==='intro'?<div className="exp-intro"><h1>South Pole Expedition</h1><div className="exp-settings"><label>Players <input type="number" min="1" step="1" value={pupils} onChange={e=>setPupils(Math.max(1,Math.floor(Number(e.target.value)||1)))}/></label><label><input type="checkbox" checked={easy} onChange={e=>setEasy(e.target.checked)}/> Gentle pace</label></div><button className="exp-gold" onClick={()=>setPhase('brief')}>Start the expedition →</button><a href="/rescue">Try the short tutorial first</a><div className="mission-picker" aria-label="Choose a mission">{missions.map((m,i)=><button key={m.name} onClick={()=>{setRound(i*3);setRun(fresh());setPhase('brief')}}><small>0{i+1}</small>{m.name}</button>)}</div><img src="/assets/rescue/appa-0.png" alt="Appa flying over the water"/></div>:<>
 <div className="exp-objective">{mission===0&&<button className="order-voice" onClick={()=>say(order.request)} aria-label="Listen to the order"><Volume2 size={23}/>{order.who}</button>}<small>MISSION {mission+1} · ROUND {part+1}</small><h1>{data.name}</h1><p>{mission===0?(run.carrying?'Bring it home!':help?order.request:'Listen to the request.'):mission===3?'Three neighbours. Three different requests.':`${data.verb} ${mission===0?'the '+target:'three '+({fish:'fish',scarf:'scarves',blanket:'blankets',boots:'pairs of boots',book:'books'}[target])}.`}</p></div>
 {mission===0&&<div className="exp-grid" ref={grid}>{Array.from({length:32},(_,i)=>{const gap=i===path[path.length-2]&&!run.bridge;return <button key={i} aria-label={`Ice ${i+1}${i===24?', home':i===31?', supplies':''}`} disabled={!active||!path.includes(i)||gap} className={(path.includes(i)&&!gap?'ice ':'water ')+(run.pos===i?'occupied':'')} onClick={()=>move(i)}>{path.includes(i)&&!gap&&<img src={art+'floe.png'} alt=""/>}{i===24&&<span>HOME</span>}{iceStops(part).filter(o=>o.pos===i&&!(run.carrying&&o.item===target)).map(o=><img key={o.item} className="grid-cargo" src={art+o.item+'.png'} alt={o.item}/>)}{gap&&<span>WATER</span>}{i===path[path.length-2]&&run.building&&<div className="bridge-building" role="img" aria-label="Katara raises water and freezes a new crossing" onAnimationEnd={e=>{if(e.animationName==='water-build'){setRun(s=>({...s,building:false,bridge:true}));setNotice('The crossing is ready. She can bend water!')}}}><div className="bridge-water"/><img className="forming-floe" src={art+'floe.png'} alt=""/></div>}</button>})}<div className="jump-shadow" style={{left:pose.x+'%',top:(pose.y+pose.air*17)+'%',opacity:1-pose.air*.65,transform:'translate(-50%,-50%) scale('+(1-pose.air*.35)+')'}}/><div key={run.jump?run.jump.from+'-'+run.jump.to:'idle-'+run.pos} className={run.jump?'katara-flight':'katara-standing'} onAnimationEnd={e=>{if(e.animationName==='katara-flight')landJump()}} style={{left:pose.x+'%',top:pose.y+'%', '--from-x':anchor(run.jump?.from??run.pos).x+'%', '--from-y':anchor(run.jump?.from??run.pos).y+'%', '--to-x':anchor(run.jump?.to??run.pos).x+'%', '--to-y':anchor(run.jump?.to??run.pos).y+'%', '--jump-duration':reduced?'160ms':'880ms','--jump-arc':reduced?'0px':'-52px'} as CSSProperties}><div className={'jump-actor '+(run.jump?'is-jumping':'is-idle')} style={{left:'50%',top:'100%',width:'100%',height:'100%'}}>{run.jump?<span className="katara-frames" role="img" aria-label="Katara jumping" style={{transform:'scaleX('+pose.facing+')'}}/>:run.building?<img src="/assets/rescue/katara-2.png" alt="Katara bending water"/>:<span className="katara-frames katara-rest" role="img" aria-label="Katara"/>}{run.carrying&&<img className="carried-cargo" src={art+target+'.png'} alt={target}/>}</div></div></div>}
 {mission===1&&<><div className="shore-katara" style={{left:shore.x,top:shore.y,width:shore.size,height:shore.size}}><div key={run.cast?'bending':'rest'} className={'shore-katara-frames '+(run.cast?'casting':'resting')} role="img" aria-label={run.cast?'Katara moves her hands to guide the water':'Katara standing on the snowy shore'} style={{backgroundPosition:(run.cast?Math.min(7,Math.floor(run.cast.elapsed/CAST_SECONDS*8))*100/7:0)+'% 0'}}/></div>{driftItems(run.time,round,easy,cargo).filter(o=>o.id!==run.cast?.id).map(o=><div key={o.id} className="floating-cargo" style={{left:o.x+'%',top:o.y+'%',transform:'translate(-50%,-50%) rotate('+Math.sin(run.time*2+o.id)*5+'deg)'}}><img className="cargo-ripple" src={art+'water-flow-0.png'} alt=""/><img src={art+o.kind+'.png'} alt={o.kind}/></div>)}<div className="water-reticle" style={{left:run.aim+'%'}}><img src={art+'water-flow-0.png'} alt=""/><span>AIM · BEND</span></div>{run.cast&&water&&<><div className="water-fountain" style={{left:water.x+'%',top:water.sourceY+'%',opacity:water.opacity}}><img src={art+'water-flow-'+water.frame+'.png'} alt="Water rises from the sea and flows toward Katara"/></div>{run.cast.kind&&<img className="caught-cargo" style={{left:water.x+'%',top:water.itemY+'%',opacity:water.opacity}} src={art+run.cast.kind+'.png'} alt={'Rescuing '+run.cast.kind}/>}</>}<div className="shore-basket">{Array.from({length:run.count},(_,i)=><img key={i} src={art+target+'.png'} alt={'Saved '+target}/>)}</div></>}
 {mission===2&&<><img className="exp-appa" style={{top:run.y+'%'}} src={'/assets/rescue/appa-'+Math.floor(run.time*5)%4+'.png'} alt="Appa"/>{objects.filter(o=>!run.used.includes(o.id)&&o.x-run.time*speed>-10&&o.x-run.time*speed<110).map(o=><img key={o.id} className={'flight-object '+(o.kind==='cloud'?'hazard':'')} style={{left:(o.x-run.time*speed)+'%',top:o.y+'%'}} src={art+o.kind+'.png'} alt={o.kind}/>)}<div className="flight-distance"><span style={{width:Math.min(100,run.time*speed/930*100)+'%'}}/></div></>}
 {mission===3&&<div className="village-people">{['Katara','Sokka','Aang'].map((name,i)=><div key={name} className={run.deliveries.includes(String(i))?'helped':''}><button className="village-request" onClick={()=>say('I need '+noun(cargo[(part+i)%5])+'. Please help me.')}><Volume2 size={18}/> {run.deliveries.includes(String(i))?'Thank you!':help?'I need '+noun(cargo[(part+i)%5])+'.':'Listen to my request'}</button><button className="village-person" aria-label={'Deliver to '+name} onClick={()=>deliver(i)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();deliver(i)}}><img src={'/assets/'+name.toLowerCase()+'.png'} alt={name}/><span>{name} {run.deliveries.includes(String(i))?'✓':''}</span></button></div>)}</div>}
 <div className="exp-bottom-hud"><span>{mission===0?`${run.count}/3 orders · ${run.moves} jumps`:mission===3?`${run.deliveries.length}/3 neighbours helped`:`${run.count}/3 supplies saved`}</span><span>{mission===2?'Cloud bumps: ':mission===1?'Practice attempts: ':''}{(mission===1||mission===2)&&run.hits}</span></div>
 </>}
 {(phase==='brief'||phase==='result'||phase==='end'||paused)&&phase!=='intro'&&<div className="exp-overlay"><div className="exp-card">{paused?<><h2>Take a breath.</h2><button className="exp-gold" onClick={()=>setPaused(false)}>Resume</button></>:phase==='end'?<><p>THE VILLAGE IS READY</p><h2>Small voices.<br/>A big adventure.</h2><p>You earned {score} stars together.</p><a className="exp-gold" href="/watch">Continue to movie time →</a><button onClick={()=>{setRound(0);setScore(0);setRun(fresh());setPhase('brief')}}>Play another expedition</button></>:phase==='result'?<><p>ROUND {round+1} COMPLETE</p><h2>You made a difference!</h2><p>Tell your team: “{mission===0?'I have got '+noun(target)+'.':mission===1?'Katara can bend water.':mission===2?'Appa can fly.':'We can help our friends.'}”</p><button className="exp-gold" onClick={()=>{if(round===11)setPhase('end');else{setRound(round+1);setRun(fresh());setNotice('');setPhase('brief')}}}>We said it. {round===11?'Finish':'Swap players'} →</button></>:<><p>MISSION {mission+1} · ROUND {part+1}</p><h2>{data.name}</h2><p>{data.subtitle}</p><div className="role-list">{['Pilot','Navigator','Speaker'].map((role,i)=><span key={role}>{role}<b>Player {playerRoles[i]}</b></span>)}</div><p>{mission===0?'Listen to a friend’s request. Find the correct supply and take it home. Say “Here you are!” Three different orders; swap players after each delivery.':mission===1?'Move the aim under the correct floating item. Press Bend water to catch it. Save three.':mission===2?'Use ↑ ↓ or touch the sky to steer. Collect three requested items. Avoid wind clouds. The route loops if you need another try.':'Listen to each neighbour. Select a supply, then select its owner. Help all three.'}</p><button className="exp-gold" onClick={()=>{setPhase('play');setPaused(false)}}>Our team is ready →</button></>}</div></div>}
 </section>
 {phase!=='intro'&&<section className="exp-console"><div><small>NAVIGATOR & SPEAKER</small><p>{mission===0?(run.carrying?'I have got '+noun(target)+'.':help?'Can you find '+noun(target)+'?':'Tell your pilot where to go.'):(help?data.phrase:'Give your pilot an English command.')}</p><button onClick={()=>say(mission===0?order.request:data.phrase)}><Volume2 size={17}/> Listen</button><label><input type="checkbox" checked={help} onChange={e=>setHelp(e.target.checked)}/> Sentence support</label></div><div className="exp-controls">{mission===0&&<><span className="current-speaker">Pilot {playerRoles[0]} · Speaker {playerRoles[2]}</span>{!run.carrying&&iceStops(part).some(o=>o.pos===run.pos)&&<button disabled={!active||!!run.jump} onClick={()=>{const found=iceStops(part).find(o=>o.pos===run.pos);if(found?.item===target){setRun(s=>({...s,carrying:true}));setNotice('Yes! Tell your team: I have got '+noun(target)+'.')}else setNotice('That is '+noun(found?.item||'different item')+'. Listen to the request again.')}}>Take it</button>}{run.carrying&&run.pos===24&&<button className="exp-gold" disabled={!active||!!run.jump} onClick={()=>{setRun(s=>s.carrying&&s.pos===24?({...s,carrying:false,count:s.count+1}):s);setNotice('Thank you! Swap players for the next order.')}}>Here you are! →</button>}</>}{mission===0&&<button disabled={!active||run.bridge||run.building||!!run.jump} onClick={()=>{setRun(s=>({...s,building:true}));setNotice('Watch Katara lift the water and freeze the crossing!')}}>Bend water · open crossing</button>}{mission===1&&<button className="exp-gold" disabled={!active||!!run.cast} onClick={catchIt}>Bend water! <small>Space</small></button>}{mission===2&&<>{[-1,1].map(dir=><button key={dir} disabled={!active} onClick={()=>setRun(s=>({...s,y:Math.max(12,Math.min(84,s.y+dir*12))}))}>{dir<0?'↑ Fly up':'↓ Fly down'}</button>)}</>}{mission===3&&cargo.map(item=><button key={item} disabled={!active} aria-pressed={run.selected===item} draggable onDragStart={()=>setRun(s=>({...s,selected:item}))} onClick={()=>setRun(s=>({...s,selected:item}))}><img src={art+item+'.png'} alt=""/>{item}</button>)}</div><p role="status">{notice}</p></section>}
 
 <Dialog open={restart} onOpenChange={setRestart}><DialogContent><DialogTitle>Start a new expedition?</DialogTitle><DialogDescription>This clears the current expedition and stars.</DialogDescription><button className="exp-gold" onClick={()=>{setRun(fresh());setScore(0);setRound(0);setPhase('intro');setPaused(false);setRestart(false)}}>Start again</button><button onClick={()=>setRestart(false)}>Keep playing</button></DialogContent></Dialog>
 </main>
}
