'use client';
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {ArrowRight,Compass,Users,BookOpen,Play,Trophy,Wind,Droplets,Flame,Mountain,GraduationCap,Maximize,Check,Home} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Heroes,World,Words,Watch,Challenge} from './Activities';
import Quiz from './Quiz';
import Teacher from './Teacher';
import type {Level} from '@/data/content';
import {registerGameTools} from './webmcp';
export const stages=[['heroes','Meet the heroes','Names, faces & a little magic',Users],['world','Explore the world','Four elements. Four nations.',Compass],['words','Pack your words','A little practice before we watch',BookOpen],['watch','Movie time','The Boy in the Iceberg',Play],['challenge','Story quest','Remember, connect & speak',Wind],['quiz','The final challenge','Bring your team. Find your balance.',Trophy]] as const;
export default function Game({screen}:{screen:string}){
 const [level,setLevel]=useState<Level>('explorer');const [completed,setCompleted]=useState<string[]>([]);const [ready,setReady]=useState(false);const [notice,setNotice]=useState('');
 useEffect(()=>{try{const l=localStorage.getItem('avatar-level');if(l==='challenger'||l==='explorer')setLevel(l);const p=JSON.parse(localStorage.getItem('avatar-stops')||'[]');if(Array.isArray(p))setCompleted(p.filter(x=>typeof x==='string'));}catch{}setReady(true)},[]);
 function changeLevel(v:Level){setLevel(v);try{localStorage.setItem('avatar-level',v)}catch{}}
 function finish(){const k=level+':'+screen;setCompleted(prev=>{const next=prev.includes(k)?prev:[...prev,k];try{localStorage.setItem('avatar-stops',JSON.stringify(next))}catch{}return next})}
 useEffect(()=>registerGameTools(changeLevel),[]);
 const idx=stages.findIndex(s=>s[0]===screen);const current=stages[idx];
 const levelPicker=<Tabs value={level} onValueChange={v=>changeLevel(v as Level)} className="level-tabs"><TabsList className="level-picker" aria-label="English level"><TabsTrigger value="explorer" className={level==='explorer'?'chosen':''}><span>Explorer<small>Beginner · Pre-A1 / A1</small></span></TabsTrigger><TabsTrigger value="challenger" className={level==='challenger'?'chosen':''}><span>Challenger<small>Continuing · A1+ / A2</small></span></TabsTrigger></TabsList></Tabs>;
 return <div className="game-shell"><header className="topbar"><Link className="brand" href="/"><Wind/><span>AVATAR<small>ELEMENT QUEST</small></span></Link><nav><Link className={screen==='journey'?'active':''} href="/">Your journey</Link><Link className={screen==='world'?'active':''} href="/world">The four nations</Link></nav><div className="header-tools"><button className="icon-button" title="Toggle full screen" aria-label="Toggle full screen" onClick={async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{setNotice('Full screen is not available here. You can zoom in with your browser.')}}}><Maximize size={18}/></button><Link className="teacher-link" href="/teacher"><GraduationCap size={18}/> Teacher guide</Link></div></header>
 {screen==='journey'?<main className="journey"><div className="intro"><p className="eyebrow">BOOK ONE: WATER · CHAPTER 01</p><h1>Your adventure<br/>starts with <em>air.</em></h1><p>Meet Aang and his friends. Explore their world.<br/>Learn English, one element at a time.</p>{levelPicker}<Link className="gold-button" href="/heroes">Begin your journey <ArrowRight size={19}/></Link><p className="small-note">Play together · Take your time · Help your team</p></div><div className="world-window"><img src="/assets/air.png" alt="An illustrated mountain air temple above the clouds"/><div className="window-caption"><span>YOUR MISSION</span><h2>Bring the elements together.</h2><div className="element-row"><Droplets/><Mountain/><Flame/><Wind/></div></div></div><div className="chapter-heading"><h2>One story. Six stops.</h2><span>BEFORE → WATCH → AFTER</span></div><div className="stage-grid">{stages.map(([id,title,sub,Icon],i)=><Link className="stage-card" href={'/'+id} key={id}><div className="stage-top"><Icon size={23}/><span>{completed.includes(level+':'+id)?<Check size={18}/>:('0'+(i+1))}</span></div><h3>{title}</h3><p>{sub}</p><ArrowRight size={18}/></Link>)}</div></main>:<main className="activity-main"><div className="activity-top"><Link className="back-link" href="/"><Home size={17}/> Your journey</Link>{levelPicker}</div>{screen!=='teacher'&&<nav className="stop-nav" aria-label="Journey stops">{stages.map(([id,title,,Icon],i)=><Link href={'/'+id} key={id} aria-current={id===screen?'page':undefined} className={id===screen?'active':''}><Icon size={16}/><span>{i+1}. {title}</span>{completed.includes(level+':'+id)&&<Check size={14}/>}</Link>)}</nav>}<div className="activity-title"><p className="eyebrow">{screen==='teacher'?'MOVIE CLUB · TEACHER NOTES':`STOP 0${idx+1} · ${idx<3?'BEFORE WATCHING':idx===3?'WHILE WATCHING':'AFTER WATCHING'}`}</p><h1>{current?.[1]||'Make room for every learner.'}</h1></div>{ready?<div key={level+screen}>{screen==='heroes'&&<Heroes level={level}/>} {screen==='world'&&<World level={level}/>} {screen==='words'&&<Words level={level}/>} {screen==='watch'&&<Watch level={level}/>} {screen==='challenge'&&<Challenge level={level}/>} {screen==='quiz'&&<Quiz level={level} onComplete={finish}/>} {screen==='teacher'&&<Teacher/>}</div>:<p role="status">Getting your adventure ready…</p>}{idx>=0&&idx<5&&<div className="next-stop"><p>Ready? Tell your partner one thing you remember.</p><Link className="gold-button" onClick={finish} href={'/'+stages[idx+1][0]}>Next: {stages[idx+1][1]}<ArrowRight size={19}/></Link></div>}</main>}
 {notice&&<p className="notice" role="status">{notice}</p>}<footer>AVATAR: THE LAST AIRBENDER <span>English movie club · Episode 1 · Fan-made learning activity</span></footer></div>
}
