'use client';
import {useState,useEffect} from 'react';
import {Wind,Droplets,Flame,Mountain,Trophy,Check,RotateCcw,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {quizzes,type Level} from '@/data/content';
import {AnswerCard,Speak} from './shared';
import {awardAnswer,freshQuiz,restoreQuiz,type QuizState} from './quiz-state';
const elements=[['Air',Wind],['Water',Droplets],['Earth',Mountain],['Fire',Flame]] as const;
export default function Quiz({level,onComplete}:{level:Level;onComplete:()=>void}){
 const [game,setGame]=useState<QuizState>(freshQuiz);const [ready,setReady]=useState(false);const [active,setActive]=useState<number|null>(null);const [reset,setReset]=useState(false);const [showHint,setShowHint]=useState(false);
 useEffect(()=>{try{setGame(restoreQuiz(localStorage.getItem('avatar-quiz-'+level),level))}catch{}setReady(true)},[level]);
 useEffect(()=>{if(ready)try{localStorage.setItem('avatar-quiz-'+level,JSON.stringify(game))}catch{}},[game,ready,level]);
 const bank=quizzes[level];const count=Object.keys(game.answered).length;const complete=count===bank.length;const question=active===null?null:bank[active];
 useEffect(()=>{if(complete)onComplete()},[complete]);
 function answer(choice:number){if(!question)return;setGame(prev=>awardAnswer(prev,level,question.id,choice))}
 return <><p className="lead">Choose a tile. Talk with your team. Choose one answer. Every question helps you learn.</p><div className="quiz-toolbar"><div className={'team '+(game.turn===0&&!complete?'current':'')}><Wind/><div><span>TEAM AIR</span><strong>{game.scores[0]}</strong></div>{game.turn===0&&!complete&&<small>Your turn</small>}</div><div className="quiz-middle"><span>{count} / 12 explored</span><strong>{complete?'All four elements together':level==='explorer'?'Explorer challenge':'Challenger challenge'}</strong></div><div className={'team '+(game.turn===1&&!complete?'current':'')}><Droplets/><div><span>TEAM WATER</span><strong>{game.scores[1]}</strong></div>{game.turn===1&&!complete&&<small>Your turn</small>}</div></div>
 {complete&&<div className="celebration" role="status"><Trophy size={46}/><h2>{game.scores[0]===game.scores[1]?'A perfect team balance!':`${game.scores[0]>game.scores[1]?'Team Air':'Team Water'} wins the challenge!`}</h2><p>Both teams have explored all four elements. Choose one new word and one sentence to take home.</p><p className="reflection">I can name a hero. · I can say where they are from. · I can talk about the story.</p></div>}
 <div className="quiz-board">{elements.map(([name,Icon],col)=><div className={'quiz-column '+name.toLowerCase()} key={name}><div className="quiz-column-title"><Icon/><h2>{name}</h2>{bank.slice(col*3,col*3+3).every(q=>game.answered[q.id])&&<Check size={20}/>}</div>{bank.slice(col*3,col*3+3).map((q,row)=>{const done=game.answered[q.id];return <button disabled={!ready} className={'quiz-tile '+(done?'done':'')} key={q.id} onClick={()=>{setActive(col*3+row);setShowHint(false)}} aria-label={done?`Review question ${col*3+row+1}`:`Open ${name} question for ${(row+1)*100} points`}><span>{done?<Check size={36}/>:(row+1)*100}</span><small>{done?'Review answer':q.category}</small></button>})}</div>)}</div><div className="quiz-bottom"><p>No timer. Think together. Read the feedback after every answer.</p><button className="soft-button" onClick={()=>setReset(true)}><RotateCcw size={17}/> Restart this level</button></div>
 <Dialog open={active!==null} onOpenChange={open=>{if(!open)setActive(null)}}><DialogContent className="quiz-dialog"><DialogTitle>{question?.category} · {active===null?'':((active%3)+1)*100} points</DialogTitle><DialogDescription>{question&&game.answered[question.id]?'Review together. This question has already been scored.':`Team ${game.turn===0?'Air':'Water'}: talk first, then choose.`}</DialogDescription>{question&&<div className="answer-card"><div className="question-row">{question.image&&(level==='explorer'||!['c1','c3'].includes(question.id)||game.answered[question.id])&&<img className="question-image" src={'/assets/'+question.image+'.png'} alt="Visual clue from the Avatar world"/>}<h2>{question.prompt}</h2></div><Speak text={question.prompt+' '+question.options.join('. ')}/><div className="answer-options">{question.options.map((o,i)=>{const saved=game.answered[question.id];return <button key={o} disabled={!!saved} className={saved?(i===question.answer?'correct':saved.choice===i?'incorrect':''):''} onClick={()=>answer(i)}><span>{String.fromCharCode(65+i)}</span>{o}{saved&&i===question.answer&&<Check size={18}/>}</button>})}</div>{game.answered[question.id]?<div className="feedback" role="status"><strong>{game.answered[question.id].choice===question.answer?'Yes! Well done.':'A new thing to remember.'}</strong><p>{question.explain}</p><p className="speak-prompt">{level==='explorer'?'Say the sentence together.':'Tell your partner why this answer is correct.'}</p><button className="gold-button" onClick={()=>setActive(null)}>Back to the board <ArrowRight size={18}/></button></div>:question.hint&&<><button className="text-button" onClick={()=>setShowHint(!showHint)}>{showHint?'Hide hint':'A little help'}</button>{showHint&&<p className="hint">{question.hint}</p>}</>}</div>}</DialogContent></Dialog>
 <Dialog open={reset} onOpenChange={setReset}><DialogContent className="reset-dialog"><DialogTitle>Start this quiz again?</DialogTitle><DialogDescription>This clears the answers and both team scores for {level==='explorer'?'Explorer':'Challenger'} only.</DialogDescription><div className="button-row"><button className="gold-button" onClick={()=>{setGame(freshQuiz());setActive(null);setReset(false)}}>Restart quiz</button><button className="soft-button" onClick={()=>setReset(false)}>Keep playing</button></div></DialogContent></Dialog></>
}
