'use client';
import {useReducer,useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUp,ArrowDown,Wind,Droplets,Flame,Mountain,Volume2,VolumeX,RotateCcw,Check,Package,Home,Sparkles,Pause,Play,Maximize} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {rescueReducer,initialRescue,flightWords,homePoint,type Point} from './rescue-state';
import './rescue.css';
import AppaSprite from './AppaSprite';
const art='/assets/rescue/';
const phaseNames={intro:'A little kindness goes a long way',meet:'Meet your teammate',water:'A little waterbending',lift:'You did it!',board:'Your ride is here',fly:'Follow the words',deliver:'Welcome home',complete:'A delivery to remember'};
export default function RescueGame(){
 const [state,dispatch]=useReducer(rescueReducer,initialRescue);const [sound,setSound]=useState(false);const [voiceNotice,setVoiceNotice]=useState('');const [help,setHelp]=useState(true);const [paused,setPaused]=useState(false);const [restart,setRestart]=useState(false);const [sprite,setSprite]=useState(0);const [reduced,setReduced]=useState(false);const [artReady,setArtReady]=useState(false);const scene=useRef<HTMLDivElement>(null);const keys=useRef(new Set<string>());const live=useRef(state);live.current=state;
 const flying=state.phase==='fly';const airborne=['board','fly','deliver','complete'].includes(state.phase);const started=state.phase!=='intro';
 function say(text:string){if(!('speechSynthesis' in window)){setVoiceNotice('Your teacher can read the words aloud.');return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.78;u.onerror=()=>setVoiceNotice('Your teacher can read the words aloud.');window.speechSynthesis.speak(u)}
 const phrase=state.phase==='meet'?'She is Katara.':state.phase==='water'||state.phase==='lift'?'She can bend water.':state.phase==='board'||state.phase==='fly'?'He can fly.':'We can help.';
 useEffect(()=>{let active=true;const files=['rescue-bg.png','supplies.png','water-arc.png',...Array.from({length:4},(_,i)=>'appa-'+i+'.png'),...Array.from({length:4},(_,i)=>'katara-'+i+'.png')];Promise.all(files.map(file=>new Promise<void>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve();image.onerror=()=>reject();image.src=art+file}))).then(()=>{if(active)setArtReady(true)}).catch(()=>{if(active)setVoiceNotice('Some artwork could not load. Please reload the page to try again.')});return()=>{active=false}},[]);
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');setReduced(mq.matches);const cb=()=>setReduced(mq.matches);mq.addEventListener('change',cb);return()=>mq.removeEventListener('change',cb)},[]);
 useEffect(()=>{if(paused||restart||!artReady)return;const interval=setInterval(()=>{setSprite(s=>(s+1)%4)},80);return()=>clearInterval(interval)},[reduced,paused,restart,artReady]);
 useEffect(()=>{if(state.phase!=='lift'||paused||restart)return;const timer=setTimeout(()=>dispatch({type:'lifted'}),reduced?700:3000);return()=>clearTimeout(timer)},[state.phase,paused,reduced,restart]);
 useEffect(()=>{if(sound&&started)say(phrase);return()=>{if('speechSynthesis' in window)window.speechSynthesis.cancel()}},[state.phase,sound]);
 useEffect(()=>{if(state.phase==='complete')try{const old=JSON.parse(localStorage.getItem('avatar-stops')||'[]');if(Array.isArray(old))localStorage.setItem('avatar-stops',JSON.stringify([...new Set([...old,'explorer:rescue'])]))}catch{}},[state.phase]);
 useEffect(()=>{if(!flying||paused||restart)return;let id=0,last=0;function frame(now:number){const dt=last?Math.min((now-last)/1000,.08):0;last=now;const k=keys.current;if(k.size){const p=live.current.position;const x=(k.has('ArrowRight')||k.has('d')?1:0)-(k.has('ArrowLeft')||k.has('a')?1:0);const y=(k.has('ArrowDown')||k.has('s')?1:0)-(k.has('ArrowUp')||k.has('w')?1:0);if(x||y)dispatch({type:'target',point:{x:p.x+x*10,y:p.y+y*10}})}dispatch({type:'tick',seconds:dt});id=requestAnimationFrame(frame)}id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id)},[flying,paused,restart]);
 useEffect(()=>{if(!flying||paused||restart)return;const allowed=['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'];function down(e:KeyboardEvent){if((e.target as HTMLElement)?.closest('button,a,input,[role="dialog"]'))return;if(allowed.includes(e.key)){e.preventDefault();keys.current.add(e.key)}}function up(e:KeyboardEvent){keys.current.delete(e.key)}function clear(){keys.current.clear()}window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',clear);return()=>{clear();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',clear)}},[flying,paused,restart]);
 function steer(point:Point){if(!paused&&!restart){dispatch({type:'target',point});scene.current?.focus({preventScroll:true})}}
 function steerAt(e:React.PointerEvent<HTMLDivElement>){if(!flying||paused||restart||(e.target as HTMLElement).closest('button,a'))return;const r=e.currentTarget.getBoundingClientRect();steer({x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100});e.currentTarget.focus()}
 function nudge(dx:number,dy:number){steer({x:state.position.x+dx,y:state.position.y+dy})}
 const appaPosition=flying?state.position:state.phase==='board'?{x:54,y:40}:{x:80,y:46};
 const mission=state.phase==='meet'?(state.found?'Say hello together.':'Find Katara. Tap her to say hello.'):state.phase==='water'?(state.waterChosen?'Say the magic words together.':'Give Katara the element she needs.'):state.phase==='lift'?'Watch Katara lift the supplies.':state.phase==='board'?'Appa is ready. Tell us what he can do.':state.phase==='fly'?(state.words===3?'Take the supplies to the village.':'Guide Appa through the words in order.'):state.phase==='deliver'?'The village is waiting. Let’s help!':'The supplies are home. Thank you, team!';
 return <main className={'rescue-page '+(paused?'is-paused':'')}><header className="rescue-header"><a href="/" className="rescue-back"><ArrowLeft size={18}/><span>Back to your journey</span></a><div className="rescue-brand"><Wind/><span>APPA’S RESCUE FLIGHT<small>EXPLORER ADVENTURE</small></span></div><div className="rescue-tools"><button aria-label={sound?'Turn voice off':'Turn voice on'} title={sound?'Voice on':'Voice off'} onClick={()=>setSound(!sound)}>{sound?<Volume2 size={20}/>:<VolumeX size={20}/>}</button>{started&&state.phase!=='complete'&&<button aria-label={paused?'Resume adventure':'Pause adventure'} onClick={()=>{keys.current.clear();setPaused(!paused)}}>{paused?<Play size={19}/>:<Pause size={19}/>}</button>}<button aria-label="Restart adventure" onClick={()=>setRestart(true)}><RotateCcw size={18}/></button></div></header>
 <div className="rescue-stage" ref={scene} tabIndex={flying?0:-1} role="region" aria-label="Interactive snowy shore. During flight, move your mouse or click a destination." onPointerDown={steerAt} onPointerMove={e=>{if(e.pointerType==='mouse'||e.buttons)steerAt(e)}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(state.phase==='water'){const kind=e.dataTransfer.getData('text/plain');if(kind)dispatch({type:'element',element:kind})}}}>
 <img className="rescue-bg" src={art+'rescue-bg.png'} alt="Cartoon snowy shore with a Water Tribe village across the sea" draggable={false}/><div className="rescue-shade"/>
 <div className="rescue-snow" aria-hidden="true">{Array.from({length:16},(_,i)=><i key={i} style={{left:(i*6.3)+'%',animationDelay:(-i*.7)+'s',animationDuration:(5+i%4)+'s'}}/>)}</div>
 {started&&<div className="rescue-hud"><span className="mission-pill"><Package size={17}/>{airborne?'Supplies on board':'Rescue the supplies'}</span><div className="rescue-chapters" aria-label="Adventure progress">{['Meet','Help','Fly','Home'].map((s,i)=>{const chapter=state.phase==='meet'?0:['water','lift'].includes(state.phase)?1:['board','fly'].includes(state.phase)?2:3;return <span key={s} className={i<=chapter?'lit':''}>{i<chapter?<Check size={13}/>:i+1}<small>{s}</small></span>})}</div></div>}
 {state.phase==='intro'?<div className="rescue-intro"><p className="rescue-kicker">A SMALL MISSION. A BIG ADVENTURE.</p><h1>A helping hand.<br/><em>A flying friend.</em></h1><p>Katara’s supplies are stuck on the ice.<br/>Help her bring them home with Appa.</p><button className="rescue-primary" disabled={!artReady} onClick={()=>dispatch({type:'start'})}>{artReady?'Let’s help!':'Loading artwork…'} <ArrowRight size={22}/></button><span className="rescue-intro-note">Look · Play · Say it together</span><img className="intro-appa" src={art+'appa-'+sprite+'.png'} alt="Appa, the flying bison" draggable={false}/></div>:<>
 {['meet','water','lift'].includes(state.phase)&&<button className={'katara-sprite '+(state.found?'found':'beckon')} aria-label={state.phase==='meet'?'Say hello to Katara':'Give water to Katara'} onClick={()=>{if(state.phase==='meet')dispatch({type:'find'});else if(state.phase==='water'&&state.waterChosen)dispatch({type:'bend'})}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();e.stopPropagation();dispatch({type:'element',element:e.dataTransfer.getData('text/plain')})}}><img src={art+'katara-'+(state.phase==='lift'?2:state.waterChosen?1:state.found?3:0)+'.png'} alt="Katara" draggable={false}/>{state.phase==='meet'&&!state.found&&<span className="character-callout">Hello! <Sparkles size={18}/></span>}{state.phase==='water'&&<span className={'drop-target '+(state.waterChosen?'ready':'')}><Droplets size={24}/>{state.waterChosen?'Ready!':'Drop water here'}</span>}</button>}
 {['meet','water','lift'].includes(state.phase)&&<img className={'supply-sprite '+(state.phase==='lift'?'lifting':'')} src={art+'supplies.png'} alt="A bundle of supplies stuck on an ice floe" draggable={false}/>}
 {state.phase==='lift'&&<img className="water-magic" src={art+'water-arc.png'} alt="Katara bends water to lift the supplies" draggable={false}/>}
 {airborne&&<div className={'appa-player '+(flying?'flying':'hovering')+(state.phase==='complete'?' home':'')} style={{left:appaPosition.x+'%',top:appaPosition.y+'%'}}><AppaSprite paused={paused||restart} tilt={flying&&state.target?(state.target.y-state.position.y)*.8:0} alt="Appa carrying the rescued supplies"/>{state.phase!=='complete'&&<img className="appa-cargo" src={art+'supplies.png'} alt="" draggable={false}/>}</div>}
 {flying&&<><div className="flight-words">{flightWords.map((w,i)=>i>=state.words&&<button key={w.text} aria-label={'Fly to word '+w.text} className={'sky-word '+(i===state.words?'next-word':'later-word')} style={{left:w.x+'%',top:w.y+'%'}} onClick={()=>steer(w)}><span>{w.text}</span>{i===state.words&&<small>Fly here</small>}</button>)}</div>{state.words===3&&<button className="home-target" style={{left:homePoint.x+'%',top:homePoint.y+'%'}} onClick={()=>steer(homePoint)}><Home size={26}/><span>Home</span></button>}<div className="collected-sentence" aria-label="Collected words">{flightWords.map((w,i)=><span key={w.text} className={i<state.words?'collected':''}>{i<state.words?w.text:'•••'}</span>)}</div><div className="flight-controls" aria-label="Flight controls"><button aria-label="Fly up" onClick={()=>nudge(0,-13)}><ArrowUp/></button><div><button aria-label="Fly left" onClick={()=>nudge(-13,0)}><ArrowLeft/></button><button aria-label="Fly down" onClick={()=>nudge(0,13)}><ArrowDown/></button><button aria-label="Fly right" onClick={()=>nudge(13,0)}><ArrowRight/></button></div></div></>}
 {state.phase==='complete'&&<div className="rescue-complete"><span className="rescue-medal"><Check size={38}/></span><p className="rescue-kicker">MISSION COMPLETE</p><h2>You made a difference.</h2><p>Katara has her supplies.<br/>The village has a little more warmth.</p><div className="rescue-recall"><span>She is Katara.</span><span>She can bend water.</span><span>He can fly.</span></div><div className="rescue-end-buttons"><a className="rescue-primary" href="/expedition">Next: Expedition <ArrowRight size={19}/></a><button className="rescue-secondary" onClick={()=>dispatch({type:'restart'})}>Play again</button></div></div>}
 </>}
 {paused&&<div className="rescue-paused"><Pause size={36}/><h2>Take a little break.</h2><button className="rescue-primary" onClick={()=>setPaused(false)}>Keep adventuring <Play size={18}/></button></div>}
 </div>
 {started&&state.phase!=='complete'&&<section className="rescue-coach" aria-label="Mission and speaking prompt"><div className="coach-main"><p className="rescue-kicker">{phaseNames[state.phase]}</p><h2>{mission}</h2>{flying&&<p className="steering-tip">Move your mouse to guide Appa, or click a word to fly to it. Take your time.</p>}<p className="rescue-feedback" aria-live="polite">{state.hint}</p></div><div className="coach-action">{state.phase==='water'&&!state.waterChosen?<div className="element-offering" aria-label="Choose an element">{[[Droplets,'water'],[Flame,'fire'],[Mountain,'earth']] .map(([I,id])=>{const Icon=I as typeof Droplets;return <button key={id as string} className={'offering '+id} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',id as string)} onClick={()=>dispatch({type:'element',element:id as string})}><Icon size={30}/><span>{id as string}</span></button>})}</div>:state.phase==='lift'?<p className="magic-caption"><Sparkles/> A little help goes a long way.</p>:!flying&&<><div className="say-together"><span>SAY IT TOGETHER</span><button className="hear-phrase" aria-label="Hear the sentence" onClick={()=>say(phrase)}><Volume2 size={18}/></button><p>{help?phrase:state.phase==='meet'?'She is…':state.phase==='water'?'She can bend…':state.phase==='board'?'He can…':'We can…'}</p></div><button className="rescue-primary" disabled={paused||(state.phase==='meet'&&!state.found)} onClick={()=>dispatch({type:state.phase==='meet'?'greet':state.phase==='water'?'bend':state.phase==='board'?'board':'deliver'})}>{state.phase==='board'?'We said it. Let’s fly!':state.phase==='deliver'?'Deliver the supplies!':'We said it. Let’s go!'}<ArrowRight size={18}/></button></>}{flying&&<button className="rescue-secondary" onClick={()=>say(state.words<3?flightWords[state.words].text:'He can fly.') }><Volume2 size={18}/> Hear {state.words<3?'the next word':'the sentence'}</button>}</div></section>}
 <footer className="rescue-footer"><span>Explorer · A story-inspired adventure, not an event from the episode.</span><div>{started&&<button onClick={()=>setHelp(!help)} aria-pressed={help}>{help?'Sentence help: on':'Sentence help: off'}</button>}<span>Teacher: listen, encourage, then continue.</span></div></footer>{voiceNotice&&<p role="status" className="rescue-voice-note">{voiceNotice}</p>}
 <Dialog open={restart} onOpenChange={setRestart}><DialogContent className="reset-dialog"><DialogTitle>Start this adventure again?</DialogTitle><DialogDescription>Your flight will start from the snowy shore. The lesson and quiz scores stay as they are.</DialogDescription><div className="button-row"><button className="gold-button" onClick={()=>{dispatch({type:'restart'});setPaused(false);setRestart(false)}}>Start again</button><button className="soft-button" onClick={()=>setRestart(false)}>Keep my adventure</button></div></DialogContent></Dialog>
 </main>
}

